decision_cache:
  enable_caching: true
  max_size: 1000
gto_core:
  confidence_threshold: 0.7
  inference_timeout: 0.5
  model_type: onnx
logging:
  level: INFO
  save_decisions: true
  save_hand_history: true
models:
  gto_core_path: models/gto_core_v1.onnx
  hand_strength_path: models/hand_strength_estimator.onnx
opponent_modeling:
  history_window: 100
  stats_to_track:
  - vpip
  - pfr
  - af
  - wtsd
  update_frequency: 10
performance:
  max_inference_time: 0.8
  onnx_providers:
  - CUDAExecutionProvider
  - CPUExecutionProvider
  parallel_processing: true
player_style:
  aggression: 0.5
  tightness: 0.5
synthesizer:
  bluff_frequency_adjustment: 0.05
  exploit_weight: 0.4
  gto_weight: 0.6
  high_confidence_threshold: 0.8
  loose_player_value_bet_threshold: 0.6
  min_confidence_threshold: 0.3
  module_weights:
    gto: 0.4
    hand_strength: 0.2
    heuristics: 0.3
    opponents: 0.1
  tight_player_equity_multiplier: 1.15
  uncertainty_threshold: 0.6
